### ISSUE TITLE
Unity push notification problem

### ISSUE THREAD

**Issue by ivanwidyan** [Pushwoosh/pushwoosh-unity#22]
Hello I'm currently working on a project that requires me to do the push notification from the outside of app. So we don't have to open the app to get the push notification. I see from this video: https://www.youtube.com/watch?v=-PfpU5-uCkM that we can push a notification from the Push Woosh website and also get it even if we're not using the app.

I've did the GCM part and I guess my app already integrated with the Push Woosh cause I already see a subscriber and it's from my phone as you can see in the picture.

![image](https://cloud.githubusercontent.com/assets/12959761/22203788/fc30faa4-e16e-11e6-9ab3-88709ec8057e.png)

But the problem is when I try to push a message from the Push Woosh website it doesn't work and I guess I need to fix it from the validation of android manifest by Push Woosh. So then I put everything and it still doesn't work. But when I try to put <services> in the android manifest, it becomes error in the Unity console. This is the outcome:

![image](https://cloud.githubusercontent.com/assets/12959761/22203910/89354338-e16f-11e6-83f5-4a23d4891848.png)

I don't know what to do anymore, is there anyone that can help me?

**Comment by DimanAM** [comment]
If you use [Pushwoosh.unitypackage](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/Pushwoosh-1.10.0.unitypackage) for Unity5 there is no need to validate manifest since most of the Pushwoosh Android components are already added through [Pushwoosh.aar](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Plugins/Android/Pushwoosh.aar). You should only add package-specific components as in [example](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Plugins/Android/AndroidManifest.xml).
