### ISSUE TITLE
Pushwoosh.Instance.GetLaunchNotification() is null all time

### ISSUE THREAD

**Issue by yuryshumovsky** [Pushwoosh/pushwoosh-unity#51]
Hi,

I try to implement some custom action when user open notification. 
When app is running in focus or in background I can get my data at OnPushNotificationsOpened

But when app is close and user open it through notification, OnPushNotificationsOpened isn't called

At start I try to read Pushwoosh.Instance.GetLaunchNotification(), but the value every-time is null
"Pass additional Custom Data to the app" field is not empty.

I do it like in the example
https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Scripts/PushNotificator.cs

Coud you help me? How to read custom data when app is closed through notification?

**Comment by wfhm** [comment]
@yuryshumovsky,

It is a known issue, and it was fixed in 5.23.1 release of our native iOS SDK. The Unity plugin was not yet updated to reflect the changes. We are going to update all the plugins shortly, the ETA for Unity is the end of May/early June.

**Comment by wfhm** [comment]
@yuryshumovsky,

The plugin is updated, please try the new version and let us know about the results.

**Comment by yuryshumovsky** [comment]
@wfhm 
I have updated SDK from package Pushwoosh-6.0.3.unitypackage + AddNotificationServiceExtensioniOS.cs from examples. 

BUT Pushwoosh.Instance.GetLaunchNotification()  still returns null in all cases 
- app is oppennig from push
- and app is already open

We use Unity 2019.2.20 and iOS 13.5 and 13.3
Was tested on iPhone XS Max, iPhone XR

**Comment by wfhm** [comment]
@yuryshumovsky,

Checking it.

**Comment by wfhm** [comment]
@yuryshumovsky,


> BUT Pushwoosh.Instance.GetLaunchNotification() still returns null in all cases
> - app is oppennig from push
> - and app is already open


`GetLaunchNotification() `​is only called when the app was closed and opened via a push notification, so it should not be called if the app was in foreground or if it was brought to foreground from background state. Could you please confirm that it is never called when the app is opened from a completely closed state too?

Also, the easiest way to read custom data from a push notification is to intercept it with OnPushNotificationsOpened callback - the issue with the callback not firing when an app is opened from a completely closed state was fixed with the latest release, so it should work out of the box.
