### ISSUE TITLE
[Unity SDK 5.22.3] iOS11 OnFailedToRegisteredForPushNotifications not working

### ISSUE THREAD

**Issue by z-guohui-qian** [Pushwoosh/pushwoosh-unity#54]
Hi,
We are testing OnFailedToRegisteredForPushNotifications and find that in iOS11 OnFailedToRegisteredForPushNotifications not called when user select to forbid notification.
It's working in iOS12~iOS14.

**Comment by wfhm** [comment]
@z-guohui-qian,

This is the expected behavior. The permission dialog asks for allowance **to show notifications,** not **to receive pushes**. This means that a device still gets a push token from APNS, so it can receive silent updates without notifying a user. In iOS 11 and lower, you cannot track whether a user allows notifications, so the fail callback only fires when a device fails to receive a push token from APNS (i.e. when a device is not connected to the internet). With iOS 12 Apple added ability to control additional authorization options, so, starting with iOS 12, OnFailedToRegisteredForPushNotifications can also be called when a user clicks Don't Allow.
